# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
# created-by: conda 24.11.3
@EXPLICIT
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2025.1.31-h56e8100_0.conda
https://conda.anaconda.org/conda-forge/noarch/font-ttf-dejavu-sans-mono-2.37-hab24e00_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/font-ttf-inconsolata-3.000-h77eed37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/font-ttf-source-code-pro-2.038-h77eed37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/font-ttf-ubuntu-0.83-h77eed37_3.conda
https://conda.anaconda.org/conda-forge/win-64/intel-openmp-2024.2.1-h57928b3_1083.conda
https://conda.anaconda.org/conda-forge/win-64/python_abi-3.9-5_cp39.conda
https://conda.anaconda.org/conda-forge/noarch/tzdata-2025a-h78e105d_0.conda
https://conda.anaconda.org/conda-forge/win-64/ucrt-10.0.22621.0-h57928b3_1.conda
https://conda.anaconda.org/conda-forge/noarch/fonts-conda-forge-1-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libwinpthread-12.0.0.r4.gg4f2fc60ca-h57928b3_9.conda
https://conda.anaconda.org/conda-forge/win-64/vc14_runtime-14.42.34433-h6356254_24.conda
https://conda.anaconda.org/conda-forge/noarch/fonts-conda-ecosystem-1-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libgomp-14.2.0-h1383e82_1.conda
https://conda.anaconda.org/conda-forge/win-64/vc-14.3-h5fd82a7_24.conda
https://conda.anaconda.org/conda-forge/win-64/vs2015_runtime-14.42.34433-hfef2bbc_24.conda
https://conda.anaconda.org/conda-forge/win-64/_openmp_mutex-4.5-2_gnu.conda
https://conda.anaconda.org/conda-forge/win-64/bzip2-1.0.8-h2466b09_7.conda
https://conda.anaconda.org/conda-forge/win-64/double-conversion-3.3.1-he0c23c2_0.conda
https://conda.anaconda.org/conda-forge/win-64/graphite2-1.3.13-h63175ca_1003.conda
https://conda.anaconda.org/conda-forge/win-64/icu-75.1-he0c23c2_0.conda
https://conda.anaconda.org/conda-forge/win-64/lerc-4.0.0-h63175ca_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libbrotlicommon-1.1.0-h2466b09_2.conda
https://conda.anaconda.org/conda-forge/win-64/libdeflate-1.23-h9062f6e_0.conda
https://conda.anaconda.org/conda-forge/win-64/libexpat-2.6.4-he0c23c2_0.conda
https://conda.anaconda.org/conda-forge/win-64/libffi-3.4.6-h537db12_0.conda
https://conda.anaconda.org/conda-forge/win-64/libiconv-1.18-h135ad9c_1.conda
https://conda.anaconda.org/conda-forge/win-64/libjpeg-turbo-3.0.0-hcfcfb64_1.conda
https://conda.anaconda.org/conda-forge/win-64/liblzma-5.6.4-h2466b09_0.conda
https://conda.anaconda.org/conda-forge/win-64/libsqlite-3.49.1-h67fdade_1.conda
https://conda.anaconda.org/conda-forge/win-64/libwebp-base-1.5.0-h3b0e114_0.conda
https://conda.anaconda.org/conda-forge/win-64/libzlib-1.3.1-h2466b09_2.conda
https://conda.anaconda.org/conda-forge/win-64/openssl-3.4.1-ha4e3fda_0.conda
https://conda.anaconda.org/conda-forge/win-64/pixman-0.44.2-had0cd8c_0.conda
https://conda.anaconda.org/conda-forge/win-64/qhull-2020.2-hc790b64_5.conda
https://conda.anaconda.org/conda-forge/win-64/tk-8.6.13-h5226925_1.conda
https://conda.anaconda.org/conda-forge/win-64/krb5-1.21.3-hdf4eb48_0.conda
https://conda.anaconda.org/conda-forge/win-64/libbrotlidec-1.1.0-h2466b09_2.conda
https://conda.anaconda.org/conda-forge/win-64/libbrotlienc-1.1.0-h2466b09_2.conda
https://conda.anaconda.org/conda-forge/win-64/libgcc-14.2.0-h1383e82_1.conda
https://conda.anaconda.org/conda-forge/win-64/libintl-0.22.5-h5728263_3.conda
https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.47-had7236b_0.conda
https://conda.anaconda.org/conda-forge/win-64/libxml2-2.13.6-he286e8c_0.conda
https://conda.anaconda.org/conda-forge/win-64/pcre2-10.44-h3d7b363_2.conda
https://conda.anaconda.org/conda-forge/win-64/python-3.9.21-h37870fc_1_cpython.conda
https://conda.anaconda.org/conda-forge/win-64/zstd-1.5.7-hbeecb71_0.conda
https://conda.anaconda.org/conda-forge/win-64/brotli-bin-1.1.0-h2466b09_2.conda
https://conda.anaconda.org/conda-forge/noarch/certifi-2025.1.31-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/cycler-0.12.1-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/win-64/freetype-2.12.1-hdaf720e_2.conda
https://conda.anaconda.org/conda-forge/win-64/kiwisolver-1.4.7-py39h2b77a98_0.conda
https://conda.anaconda.org/conda-forge/win-64/libclang13-19.1.7-default_ha5278ca_1.conda
https://conda.anaconda.org/conda-forge/win-64/libglib-2.82.2-h7025463_1.conda
https://conda.anaconda.org/conda-forge/win-64/libhwloc-2.11.2-default_ha69328c_1001.conda
https://conda.anaconda.org/conda-forge/win-64/libtiff-4.7.0-h797046b_3.conda
https://conda.anaconda.org/conda-forge/win-64/libxslt-1.1.39-h3df6e99_0.conda
https://conda.anaconda.org/conda-forge/noarch/munkres-1.1.4-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/packaging-24.2-pyhd8ed1ab_2.conda
https://conda.anaconda.org/conda-forge/win-64/pthread-stubs-0.4-h0e40799_1002.conda
https://conda.anaconda.org/conda-forge/noarch/pyparsing-3.2.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/setuptools-75.8.0-pyhff2d567_0.conda
https://conda.anaconda.org/conda-forge/noarch/six-1.17.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/tornado-6.4.2-py39ha55e580_0.conda
https://conda.anaconda.org/conda-forge/win-64/unicodedata2-16.0.0-py39ha55e580_0.conda
https://conda.anaconda.org/conda-forge/noarch/wheel-0.45.1-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/win-64/xorg-libxau-1.0.12-h0e40799_0.conda
https://conda.anaconda.org/conda-forge/win-64/xorg-libxdmcp-1.1.5-h0e40799_0.conda
https://conda.anaconda.org/conda-forge/noarch/zipp-3.21.0-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/win-64/brotli-1.1.0-h2466b09_2.conda
https://conda.anaconda.org/conda-forge/win-64/fontconfig-2.15.0-h765892d_1.conda
https://conda.anaconda.org/conda-forge/noarch/importlib_resources-6.5.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/lcms2-2.17-hbcf6048_0.conda
https://conda.anaconda.org/conda-forge/win-64/libxcb-1.17.0-h0e4246c_0.conda
https://conda.anaconda.org/conda-forge/win-64/openjpeg-2.5.3-h4d64b90_0.conda
https://conda.anaconda.org/conda-forge/noarch/pip-25.0.1-pyh8b19718_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.9.0.post0-pyhff2d567_1.conda
https://conda.anaconda.org/conda-forge/win-64/tbb-2021.13.0-h62715c5_1.conda
https://conda.anaconda.org/conda-forge/win-64/cairo-1.18.2-h5782bbf_1.conda
https://conda.anaconda.org/conda-forge/win-64/fonttools-4.56.0-py39hf73967f_0.conda
https://conda.anaconda.org/conda-forge/noarch/importlib-resources-6.5.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/mkl-2024.2.2-h66d3029_15.conda
https://conda.anaconda.org/conda-forge/win-64/pillow-11.1.0-py39h73ef694_0.conda
https://conda.anaconda.org/conda-forge/win-64/harfbuzz-10.2.0-h885c0d4_0.conda
https://conda.anaconda.org/conda-forge/win-64/libblas-3.9.0-31_h641d27c_mkl.conda
https://conda.anaconda.org/conda-forge/win-64/libcblas-3.9.0-31_h5e41251_mkl.conda
https://conda.anaconda.org/conda-forge/win-64/liblapack-3.9.0-31_h1aa476e_mkl.conda
https://conda.anaconda.org/conda-forge/win-64/qt6-main-6.8.2-h1259614_0.conda
https://conda.anaconda.org/conda-forge/win-64/numpy-2.0.2-py39h60232e0_1.conda
https://conda.anaconda.org/conda-forge/win-64/pyside6-6.8.2-py39h0285922_0.conda
https://conda.anaconda.org/conda-forge/win-64/contourpy-1.3.0-py39h2b77a98_2.conda
https://conda.anaconda.org/conda-forge/win-64/scipy-1.13.1-py39h1a10956_0.conda
https://conda.anaconda.org/conda-forge/win-64/matplotlib-base-3.9.4-py39h5376392_0.conda
https://conda.anaconda.org/conda-forge/win-64/matplotlib-3.9.4-py39hcbf5309_0.conda
